name: Git Flow PROD Workload
on:
  pull_request:
    branches:
      - prod
  push:
    branches:
      - prod
env:
  TERRAFORM_VERSION: 1.0.8
  AWS_ROLE_ARN_PROD: arn:aws:iam::416419186814:role/pw-prod-terraform-state-manager
  AWS_S3_ARTIFACTS_BUCKET_NAME: pw-prod-terraform-github-artifacts
  AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
  AWS_DEFAULT_REGION: eu-central-1
jobs:
  TerraformPlanProd:
    name: Plan tfm Prod
    runs-on: ubuntu-latest
    environment: 'prod'
    concurrency:
      group: prod-workload
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Configure AWS
        run: |
          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: actions/checkout@v2

      - name: Copy Prod Terraform Backend config
        run: cp ./backends/remote-backend-config-prod.tf .

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        id: init
        run: |
          terraform version
          terraform init
          bash scripts/init-workspace.sh prod
          terraform workspace select prod

      - name: Terraform plan
        id: plan
        run: |
          terraform plan -var-file=tfvars/prod.tfvars -input=false -no-color -out plan-file
        continue-on-error: true

      - name: Save Terraform Plan as PR Comment
        uses: actions-ecosystem/action-create-comment@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.plan.outputs.stdout }}

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Prepare artifact
        run: |
          tar cf plan-prod.tar plan-file .terraform

      - name: Upload artifact
        if: github.event.ref == 'refs/heads/prod' && github.event_name == 'push'
        run: |
          export GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo $GIT_HASH
          aws s3 cp plan-prod.tar s3://$AWS_S3_ARTIFACTS_BUCKET_NAME/$GIT_HASH/plan-prod.tar --no-progress

  TerraformApplyProd:
    name: Apply tfm Prod
    if: github.event.ref == 'refs/heads/prod' && github.event_name == 'push'
    needs: [TerraformPlanProd]
    environment: 'prod'
    concurrency:
      group: prod-workload
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS
        run: |
          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: actions/checkout@v2

      - name: Copy Prod Terraform Backend config
        run: cp ./backends/remote-backend-config-prod.tf .

      - name: Download Artifact
        run: |
          export GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo $GIT_HASH
          aws s3 cp s3://$AWS_S3_ARTIFACTS_BUCKET_NAME/$GIT_HASH/plan-prod.tar  plan-prod.tar --no-progress

      - name: Unzip artifact
        run: |
          tar xf plan-prod.tar

      - name: Terraform init
        id: init
        run: |
          terraform version
          terraform init

      - name: Terraform apply
        run: |
          terraform apply -auto-approve -no-color -input=false plan-file

